import assert from 'node:assert/strict';
import { expect } from '@playwright/test';

/** Public runnable examples, including keyboard focus and semantic state. */
export async function verifyReleaseExamples(page, url) {
  await page.setViewportSize({width:1280,height:1000});
  await page.goto(url);
  await page.getByRole('button',{name:'Start inspecting',exact:true}).click();
  const gear=page.getByRole('button',{name:'Inspection settings',exact:true});
  await gear.focus();
  await page.keyboard.press('Tab');
  await page.keyboard.press('Shift+Tab');
  await expect(gear).toBeFocused();
  assert(await gear.evaluate(node=>getComputedStyle(node).outlineStyle !== 'none' && parseFloat(getComputedStyle(node).outlineWidth)>0),'Keyboard gear focus is visibly indicated');
  await gear.press('Enter');
  await expect(gear).toHaveAttribute('aria-expanded','true');
  await page.getByRole('checkbox',{name:'Component inspection',exact:true}).uncheck();
  await expect(page.getByRole('checkbox',{name:'Component inspection',exact:true})).not.toBeChecked();
  await page.getByRole('checkbox',{name:'Component inspection',exact:true}).check();
  await page.getByRole('button',{name:'Close settings',exact:true}).press('Enter');
  await expect(gear).toBeFocused();
  const counter=page.getByRole('button',{name:'Count: 0',exact:true});
  await counter.scrollIntoViewIfNeeded();
  await counter.hover();
  await expect(page.getByRole('complementary',{name:'Counter context',exact:true})).toBeVisible();
  const pin=page.getByRole('button',{name:'Pin Counter',exact:true});
  await pin.focus();
  await pin.press('Enter');
  await expect(pin).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Explain the interaction',exact:true}).click();
  await expect(page.getByRole('button',{name:'Show less',exact:true})).toBeVisible();
  await counter.click();
  await expect(page.getByRole('button',{name:'Count: 1',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Dismiss component context',exact:true}).press('Enter');
  await expect(pin).toBeFocused();
  await expect(pin).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button',{name:'Focus through app ref',exact:true}).click();
  await expect(page.getByRole('button',{name:'Existing button',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'Existing button',exact:true}).press('Enter');
  await expect(page.getByRole('button',{name:'Count: 2',exact:true})).toHaveCount(1);
  await page.getByRole('button',{name:'Unmount target',exact:true}).click();
  await expect(page.getByRole('button',{name:'Existing button',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Restore target',exact:true}).click();
  await page.locator('.delivery-portal').hover();
  await expect(page.getByRole('complementary',{name:'Delivery group context',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Try a failing promise',exact:true}).click();
  const log=page.getByRole('region',{name:'Live events',exact:true});
  await expect(log.locator('article').filter({hasText:'Check availability'}).locator('[data-state]')).toHaveText('failed');
  await page.getByRole('button',{name:'Report an outcome',exact:true}).click();
  await expect(log.locator('article').filter({hasText:'Background signal'}).locator('[data-state]')).toHaveText('succeeded');
  await page.getByRole('button',{name:'Run wrapped handler',exact:true}).click();
  await expect(page.getByText('Application results: 1.',{exact:true})).toBeVisible();
  await expect(log.locator('article').filter({hasText:'Local action'}).locator('[data-state]')).toHaveText('succeeded');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'Report an outcome',exact:true}).click();
  await expect(log.locator('article').first()).toHaveCSS('animation-name','none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  console.log('PASS release examples: nested counter, keyboard pin/dismiss/focus/states, composed ref, group portal, promise failure/outcome/handler, reduced-motion events.');
}
